name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\activate
          pip install -r requirements.txt
      - name: Run tests
        run: |
          venv\Scripts\activate
          pytest tests/
